### ISSUE TITLE
请问下  能用在  fragment中 么？？？   我在用  gradual  

### ISSUE THREAD

**Issue by AngelYHY** [supercwn/SuperRecycleView#1]
然后   加载更多   的  时候  就报出                                                                    java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
  请问下  要怎么解决？？

**Comment by supercwn** [comment]
这个异常是在fragment的报的吗 @AngelYHY

**Comment by AngelYHY** [comment]
太棒了   可以用了~，~    谢谢了~~

**Comment by supercwn** [comment]
喜欢这个库的话，可以给个star哦 @AngelYHY

**Comment by AngelYHY** [comment]
蒽咯   当我看到的那一天就star了   好炫  哈哈
