### ISSUE TITLE
多指长按的时候数组越界

### ISSUE THREAD

**Issue by ghost** [supercwn/SuperRecycleView#10]
多指长按的时候会数组越界，在SuperBaseAdapter.java这个类：
`protected final void initItemClickListener(final BaseViewHolder holder) {
      ……
      ……
      ……
        if (null != mOnItemLongClickListener) {
            holder.itemView.setOnLongClickListener(new View.OnLongClickListener() {
                @Override
                public boolean onLongClick(View v) {
                    final int position = holder.getAdapterPosition() - getHeaderViewCount() - 1;             
                    mOnItemLongClickListener.onItemLongClick(v, mData.get(position), position);
                    return true;
                }
            });
        }
    }`
多指长按的时候holder.getAdapterPosition() 有一定的概率等于-1，数组就越界了。
我自己加上了判断
`if (position < 0)
        return true;`

**Comment by supercwn** [comment]
好的，谢谢反馈
