### ISSUE TITLE
DragAdapter使用两种布局时，拖拽异常，碰到相同的布局才会改变位置。

### ISSUE THREAD

**Issue by g19980115** [supercwn/SuperRecycleView#13]
public class DragAdapter extends SuperBaseDragAdapter {
    public DragAdapter(Context context, List data) {
        super(context, data);
    }

    @Override
    protected void convert(BaseViewHolder holder, Object item, int position) {
        if (position % 3 != 0) {
            holder.setText(R.id.itemTv_name, position + "");
        }
    }

    @Override
    protected int getItemViewLayoutId(int position, Object item) {
        if (position % 3 == 0) {
            return R.layout.item_group;
        } else {
            return R.layout.adapter_device_list;
        }
    }
}

**Comment by g19980115** [comment]
而且item会混乱，几个item都变成一样的了

**Comment by supercwn** [comment]
这个暂时只考虑一个布局的情况下呢
