### ISSUE TITLE
ChildClick 删除Item有个bug：删除第一个Item会报错，闪退

### ISSUE THREAD

**Issue by chenliuyun** [supercwn/SuperRecycleView#14]
dataList.remove(position);
 mAdapter.notifyItemRemoved(position);
 mAdapter.notifyItemRangeChanged(position, dataList.size());
代码如上
其他的都可以，就是第一个item不行
不好意思，数据线不在身边，暂时调试不了。错误信息暂时看不到

**Comment by kanshenmekan** [comment]
notifyItemRangeChanged(position, dataList.size());调用这个就会出错，直接Adapter.notifyDataSetChanged();就没问题

**Comment by supercwn** [comment]
需要减一看看有没有问题

**Comment by kanshenmekan** [comment]
上下滑动一会，有时候也不报错，没有减一

**Comment by supercwn** [comment]
就是要去减一看看有没有

**Comment by kanshenmekan** [comment]
@supercwn 没用，早就试了。

**Comment by supercwn** [comment]
是哪部分的代码

**Comment by kanshenmekan** [comment]
@supercwn 改变数据，然后刷新的时候，只能notifyDataSetChanged(); 相比ListView多出来的那几个，就会出错，notifyDataSetChanged();能用，但是就没动画了。
