### ISSUE TITLE
Nomore

### ISSUE THREAD

**Issue by Hebin320** [supercwn/SuperRecycleView#15]
Nomore可不可以做自定义View，自带的那个NoMore View有点难看

**Comment by supercwn** [comment]
可以自定义的

**Comment by Hebin320** [comment]
怎么自定义？没看到接口方法。

**Comment by supercwn** [comment]
没有提供对应的接口呢，需要自己去修改NoMore的layout

**Comment by Hebin320** [comment]
虽然能找到Nomore的layout跟对应的Java文件，但是，都是锁定不可编辑的，不知道怎么修改

**Comment by supercwn** [comment]
你需要下载下来然后依赖库，不能compile 'com.supercwn.superrecycleview:superlibrary:1.2.0'采用这种方式了
