### ISSUE TITLE
addHeader重大问题

### ISSUE THREAD

**Issue by NFLeo** [supercwn/SuperRecycleView#16]
头部添加recyclerview式gridview，第一行永远只有一个item，下面几行才整齐排列，例如9条数据分三行三列排布，则出来的效果是第一行1个，第二行3个，第三行3个，第四行2个

**Comment by supercwn** [comment]
版本不对，你试下下载项目依赖。这个问题已经修复了

**Comment by NFLeo** [comment]
我昨天引入的，我没网络引用，我是直接拷进项目的，我看你最近没代码修改啊，你是改了哪个类啊

**Comment by NFLeo** [comment]
把recyclerview换成gridview就没问题了

**Comment by supercwn** [comment]
这个问题很早就处理了
![image](https://cloud.githubusercontent.com/assets/9639657/23979592/7ade7b3a-0a35-11e7-8f42-eae1ff6fb42c.png)

**Comment by NFLeo** [comment]
确实是还有问题额，我下了你的demo运行了也是一样出问题了，我在添加头尾布局那个界面添加了一个recyclerview头，然后就会有问题
