### ISSUE TITLE
下拉刷新卡顿

### ISSUE THREAD

**Issue by Hebin320** [supercwn/SuperRecycleView#17]
我想问一下，我用这个Recyclerview，它的item里面也有个Recyclerview，然后，功能是实现了，但是下拉刷新的时候会卡顿，是什么原因？（纯文本的列表，没有加载图片，数据也是本地写的测试数据，没有进行网络请求）

**Comment by g19980115** [comment]
你下拉刷新的时候，是不是在刷新适配器notifyDataSetChanged()？

2018/4/3修改：应该是抢占焦点的问题，header的根布局加上`android:descendantFocusability="blocksDescendants"`
