### ISSUE TITLE
LayoutManager设置为Horizontal时，前后有两段空白的view

### ISSUE THREAD

**Issue by g19980115** [supercwn/SuperRecycleView#18]
LayoutManager设置为Horizontal时，前后有两段空白的view
`setLayoutManager(new LinearLayoutManager(getActivity(), HORIZONTAL, false));`
然后这样设置
`setRefreshEnabled(false);
setLoadMoreEnabled(false);` 
后面的空白view不见了，但是前面的还在
如图所示

![screen](https://cloud.githubusercontent.com/assets/25760230/25375422/36b0b3ca-29d3-11e7-81a3-ac91335a3b60.png)

**Comment by supercwn** [comment]
如果你的需求中没有要求横向也有刷新以及加载更多的话，建议你使用原生的RecycleView。因为SuperRecycleView考虑的是竖向，设置了刷新的头部宽度的大小。
