### ISSUE TITLE
使用原生RecyclerView问题

### ISSUE THREAD

**Issue by Reginer** [supercwn/SuperRecycleView#19]
使用原生的RecyclerView，点击事件里的position总是少一个。

还有个就是之前说尾部有时候会多一个空白的部分，我终于知道是为什么了。

AnimationActivity里的superRecyclerView.setLoadMoreEnabled(false);注释了就是了。

**Comment by supercwn** [comment]
你是用原生的RecyclerView，但是Adapter用的是SuperBaseAdapter吗？

**Comment by Reginer** [comment]
嗯呢。

**Comment by supercwn** [comment]
oh，这个我正在修复了，晚几天会更新上去。
