### ISSUE TITLE
可以扩展一下功能么？

### ISSUE THREAD

**Issue by gaoyl87** [supercwn/SuperRecycleView#2]
现在的headerview你限制在了arrowrefreshheader，可以改成自定义的header吗？

**Comment by supercwn** [comment]
可以的，但是需要你自己对arrowrefreshheader进行重写 @13588823551

**Comment by gaoyl87** [comment]
你可以在你的新版本中SuperBaseAdapter加入add(List<T> data);类似的方法吗？就和BaseRecyclerViewAdapterHelper这个库一样
