### ISSUE TITLE
分割线重绘

### ISSUE THREAD

**Issue by HongLr** [supercwn/SuperRecycleView#22]
添加分割线后，当遇到数据量少，充满不了屏幕时下拉刷新会导致绘制多条分割线，望重视！

![default](https://cloud.githubusercontent.com/assets/29160726/26753229/82557560-4894-11e7-93fa-3555c45c887d.png)

**Comment by supercwn** [comment]
现在的解决方法是分割线在adapter中描绘。就可以解决了

**Comment by HongLr** [comment]
没明白你说的意思。能否举个例子或贴上代码，方便其他人在这里解决这个问题。

**Comment by supercwn** [comment]
就是说在你的activity中的recycleview不设置addItemDecoration，横线在对应的adapter中的layout文件添加你所需要的横线。这样实现的效果是一样的
