### ISSUE TITLE
  楼主删除item  刷新列表失败，

### ISSUE THREAD

**Issue by 1184104588** [supercwn/SuperRecycleView#23]
list.remove(removePostion);
    notifyItemRemoved(position);
    notifyItemRangeChanged(position,getItemCount()-position);
   rv.completeRefresh(); 
  ,java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 8(offset:8).state:9刷新列表失败 总是不对。请帮忙看看呢。

**Comment by supercwn** [comment]
直接用刷新全部的列表，记忆中好像没有测试过刷新单个

**Comment by 1184104588** [comment]
楼主我测试了下如果是notifyDataSetChanged  如果列表超过一页, 列表刷新异常。

**Comment by supercwn** [comment]
我这边测试没有遇到，可以发下你的代码上来吗？

**Comment by 1184104588** [comment]
listData.remove(removePostion);
 if (listData.size() <= 0) {
                baseView.showEmpty(emptStr);
            } else {
                mRvAdapter.notifyDataSetChanged();
                rv.completeRefresh();
            }    代码如上。 以10条为一页， 当列表超过一页, 删除10以上中的一条，就为崩掉。
