### ISSUE TITLE
大大，依赖报错帮我看下啊

### ISSUE THREAD

**Issue by a1227308812** [supercwn/SuperRecycleView#26]
我把库下载下来了 ，直接分离出superlibrary出来作为一个module依赖到我的新项目里面的，但是在xml里面引用的时候就报错了
Binary XML file line #22: Error inflating class com.zwp.mysuperrecyclib.recycleview.SuperRecyclerView
我的控件名称路径也是module的绝对路径的,但是运行就是包inflater的上面这个错误啊，大大帮忙分析下啊
<com.my.mysuperrecyclib.recycleview.SuperRecyclerView
            android:id="@+id/scyc_msg_list"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>

**Comment by supercwn** [comment]
你查下SuperRecycleView中的module的layout中的xml有引用的view，对应的地址有没有都正确

**Comment by a1227308812** [comment]
![image](https://user-images.githubusercontent.com/21053292/28960425-389bf44e-7931-11e7-92f2-e73791686f1c.png)
我这边是只需要把下载下来的包里面的这一个superlibrary分离出来引用到我的项目里面就可以了吧，我看了，我在xml里面引用的你的superlibrary里面的SuperRecyclerView控件的地址是对的，但是还是报错，我断点进去看走到ArrowRefreshHeader里面的inflater就报错了，大大你再帮我分析下呢，谢谢了！
![image](https://user-images.githubusercontent.com/21053292/28960556-c0ea8c7a-7931-11e7-9c3b-117f548bf5b3.png)

**Comment by supercwn** [comment]
说明这个布局中有view有问题
