### ISSUE TITLE
GridLayoutManager问题

### ISSUE THREAD

**Issue by a1227308812** [supercwn/SuperRecycleView#30]
我在使用GridLayoutManager的时候设置一行显示4个，但是在最后运行代码的时候会在第一个位置生成一个空白，请问是什么原因啊？

**Comment by supercwn** [comment]
因为有个刷新的头部的存在

**Comment by a1227308812** [comment]
谢谢！原因找到了，我把设置layoutmanager写到了设置adapter之后造成的。

**Comment by a1227308812** [comment]
还有就是那个监听回调（onItemClick和onItemChildClick）返回的position比实际的位置大一个，并且点击到最后一个的时候会报错，说数组越界。我在你的superBaseAdapter里面改了源码，在里面去减了一个1就没问题了，现在我自己用着是没问题了。

**Comment by supercwn** [comment]
在外面减一不也一样么

**Comment by a1227308812** [comment]
嗯，难得每次都去减的。只是不知道是不是这样的问题，没见有人问这个的。
