### ISSUE TITLE
setSpanSizeLookup 无效

### ISSUE THREAD

**Issue by sun8829** [supercwn/SuperRecycleView#5]
使用SuperRecycleView setSpanSizeLookup 无效

**Comment by supercwn** [comment]
好的，我找时间看看

**Comment by csh159** [comment]
GridLayoutManager 设置会是第一个为空，从第二开始，怎么解决啊！

**Comment by supercwn** [comment]
那个问题已经修改了，https://github.com/supercwn/SuperRecycleView/blob/master/superlibrary/src/main/java/com/superrecycleview/superlibrary/adapter/SuperBaseAdapter.java
