### ISSUE TITLE
和CoordinatorLayout配合使用的时候，突然无法滚动到最底部

### ISSUE THREAD

**Issue by mozartghost** [supercwn/SuperRecycleView#6]
和CoordinatorLayout配合使用的时候，先不上拉刷新也不下拉刷新，轻轻往上拖一半，然后在appbarlayout里的视图上上下摸两下，然后继续操作RecyclerView往上拉，结果无法上拉加载更多，而且还有好多item没有显示出来就无法往上拉了。详情Q我: 一六42三三598五

**Comment by mozartghost** [comment]
activity_refresh_load_layout.xml文件如下配置

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical" >
    
    
    <TextView
                android:layout_width="fill_parent"
                android:layout_height="50dp"
                android:layout_gravity="center_vertical"
                android:drawablePadding="12dp"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:paddingLeft="15dp"
                android:text="标题栏"
                app:layout_scrollFlags="scroll|enterAlways"
                android:background="@color/colorAccent"
                android:textColor="#FFFFFFFF"
                android:textSize="18sp" />

    <android.support.design.widget.CoordinatorLayout
        android:id="@+id/cordnLyot"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true" >
        
        
        <android.support.design.widget.AppBarLayout
            android:id="@+id/appbar"
            android:layout_width="match_parent"
            android:orientation="vertical"
            android:layout_height="wrap_content"
            android:fitsSystemWindows="true" > 

            <TextView
                android:layout_width="fill_parent"
                android:layout_height="150dp"
                android:layout_gravity="center_vertical"
                android:drawablePadding="12dp"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:paddingLeft="15dp"
                android:text="广告位"
                app:layout_scrollFlags="scroll|enterAlways"
                android:background="@color/colorAccent"
                android:textColor="#FFFFFFFF"
                android:textSize="18sp" />

            <ImageView
                android:layout_width="fill_parent"
                android:layout_height="0.5dip"
                android:scaleType="fitXY"
                app:layout_scrollFlags="scroll|enterAlways"
                android:src="@color/material_grey_300" />
        </android.support.design.widget.AppBarLayout>
        
        

        <com.superrecycleview.superlibrary.recycleview.SuperRecyclerView
            android:id="@+id/super_recycle_view"
            android:layout_width="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            android:layout_height="match_parent" />
    </android.support.design.widget.CoordinatorLayout>

</LinearLayout>`

**Comment by mozartghost** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical" >
    
    
    <TextView
                android:layout_width="fill_parent"
                android:layout_height="50dp"
                android:layout_gravity="center_vertical"
                android:drawablePadding="12dp"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:paddingLeft="15dp"
                android:text="标题栏"
                app:layout_scrollFlags="scroll|enterAlways"
                android:background="@color/colorAccent"
                android:textColor="#FFFFFFFF"
                android:textSize="18sp" />

    <android.support.design.widget.CoordinatorLayout
        android:id="@+id/cordnLyot"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true" >
        
        
        <android.support.design.widget.AppBarLayout
            android:id="@+id/appbar"
            android:layout_width="match_parent"
            android:orientation="vertical"
            android:layout_height="wrap_content"
            android:fitsSystemWindows="true" > 

            <TextView
                android:layout_width="fill_parent"
                android:layout_height="150dp"
                android:layout_gravity="center_vertical"
                android:drawablePadding="12dp"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:paddingLeft="15dp"
                android:text="广告位"
                app:layout_scrollFlags="scroll|enterAlways"
                android:background="@color/colorAccent"
                android:textColor="#FFFFFFFF"
                android:textSize="18sp" />

            <ImageView
                android:layout_width="fill_parent"
                android:layout_height="0.5dip"
                android:scaleType="fitXY"
                app:layout_scrollFlags="scroll|enterAlways"
                android:src="@color/material_grey_300" />
        </android.support.design.widget.AppBarLayout>
        
        

        <com.superrecycleview.superlibrary.recycleview.SuperRecyclerView
            android:id="@+id/super_recycle_view"
            android:layout_width="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            android:layout_height="match_parent" />
    </android.support.design.widget.CoordinatorLayout>

</LinearLayout>

**Comment by mozartghost** [comment]
<   LinearLayout 
      xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:app="http://schemas.android.com/apk/res-auto"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:orientation="vertical" >

```
<TextView
            android:layout_width="fill_parent"
            android:layout_height="50dp"
            android:layout_gravity="center_vertical"
            android:drawablePadding="12dp"
            android:gravity="center_vertical"
            android:orientation="horizontal"
            android:paddingLeft="15dp"
            android:text="标题栏"
            app:layout_scrollFlags="scroll|enterAlways"
            android:background="@color/colorAccent"
            android:textColor="#FFFFFFFF"
            android:textSize="18sp" />

<android.support.design.widget.CoordinatorLayout
    android:id="@+id/cordnLyot"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true" >


    <android.support.design.widget.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:orientation="vertical"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true" > <!-- android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar" -->

        <TextView
            android:layout_width="fill_parent"
            android:layout_height="150dp"
            android:layout_gravity="center_vertical"
            android:drawablePadding="12dp"
            android:gravity="center_vertical"
            android:orientation="horizontal"
            android:paddingLeft="15dp"
            android:text="广告位"
            app:layout_scrollFlags="scroll|enterAlways"
            android:background="@color/colorAccent"
            android:textColor="#FFFFFFFF"
            android:textSize="18sp" />

        <ImageView
            android:layout_width="fill_parent"
            android:layout_height="0.5dip"
            android:scaleType="fitXY"
            app:layout_scrollFlags="scroll|enterAlways"
            android:src="@color/material_grey_300" />
    </android.support.design.widget.AppBarLayout>



    <com.superrecycleview.superlibrary.recycleview.SuperRecyclerView
        android:id="@+id/super_recycle_view"
        android:layout_width="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"
        android:layout_height="match_parent" />
</android.support.design.widget.CoordinatorLayout>

 <   /   LinearLayout>
```

**Comment by supercwn** [comment]
这种情况当初没有测试过，应该是跟CoordinatorLayout的滑动有冲突了
