### ISSUE TITLE
只设置头部不设置脚布局，然后设置分割线，最后显示会多出一行空行，然后来个分割线

### ISSUE THREAD

**Issue by Reginer** [supercwn/SuperRecycleView#7]
只设置头部不设置脚布局，然后通过addItemDecoration设置分割线，会在最后多出一行空的item，然后来个分割线。

**Comment by supercwn** [comment]
最后的那个空的item是加载更多的布局呢

**Comment by songguoping** [comment]
我也遇到这种情况了，有没有好的解决办法呢？

**Comment by supercwn** [comment]
这个我在demo中测试是没有问题的呢？你看下是不是你的写法有问题。 Reginer 有跟我私聊过，好像记得他也是写法有问题，你可以问下他

**Comment by supercwn** [comment]
@songguoping 还有一种方法是在adapter中画线，不采用addItemDecoration的方法添加

**Comment by Reginer** [comment]
这个问题，我后来没用addItemDecoration方法，在item上加了个线 。。。因为我也不知道为什么会多一条线。

**Comment by songguoping** [comment]
我这里的情况是刷新完成后会偶发性的多出一条线，谢谢你们的解决方案
